CREATE TABLE `audits` (
	`id` text PRIMARY KEY NOT NULL,
	`patient_token` text NOT NULL,
	`arrival_date` text NOT NULL,
	`triage_performed` integer DEFAULT false,
	`triage_time` text,
	`risk_level` text,
	`observation_level_met` text,
	`observer_roles` text,
	`compassionate_care` text,
	`safeguarding_check` integer DEFAULT false,
	`search_policy_followed` integer DEFAULT false,
	`clinician_seen` integer DEFAULT false,
	`risk_assessment_type` integer DEFAULT false,
	`risk_assessment_trigger` integer DEFAULT false,
	`risk_assessment_future` integer DEFAULT false,
	`risk_assessment_history` text,
	`physical_assessment` integer DEFAULT false,
	`drug_alcohol_considered` integer DEFAULT false,
	`discharge_plan_safe` integer DEFAULT false,
	`team_communication` integer DEFAULT false,
	`capacity_assessment` integer DEFAULT false,
	`referred_to_psych` integer DEFAULT false,
	`psych_review_time` text,
	`parallel_assessment` integer DEFAULT false,
	`departure_time` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
